### ISSUE TITLE
პროდუქტების გვერდზე დინამიურად მონაცემების წამოღება და ჩვენება

### ISSUE THREAD

**Issue by lashajugeli** [juglika15/my-app#2]

**Comment by IrakliAmbroladze** [comment]
სიის გაკეთება

**Comment by IrakliAmbroladze** [comment]
მე ვმუშაონ product-details branchზე. სადაც პროდუქტების სია იქნება მოცემული

**Comment by IrakliAmbroladze** [comment]
ამ ეტაპისთვის product-details branchზე ჰედერში დამატებული მაქვს products ფეიჯი, რომელსაც ბაზიდან მოაქვს პროდუქტების სათაურები

**Comment by IrakliAmbroladze** [comment]
დავასრულე სიის ფეიჯის კეთება
